import { Ionicons } from '@expo/vector-icons';
import type { NativeStackScreenProps } from '@react-navigation/native-stack';
import * as ImagePicker from 'expo-image-picker';
import * as Location from 'expo-location';
import React, { useEffect, useRef, useState } from 'react';
import { Alert, Image, Linking, Platform, Pressable, StyleSheet, Text, View } from 'react-native';
import MapView, { Marker } from 'react-native-maps';
import { io, type Socket } from 'socket.io-client';
import { AppScreen, Card, Header, Money, Pill, PrimaryButton, SecondaryButton, SectionTitle, ToggleRow, ui } from '../../components/ui';
import { API_URL } from '../../config';
import { useAuth } from '../../context/AuthContext';
import { api } from '../../services/api';
import { colors } from '../../theme';
import type { Booking, BookingStatus, RootStackParamList } from '../../types';
import { issueLabel } from '../client/HomeScreens';

type Props<T extends keyof RootStackParamList> = NativeStackScreenProps<RootStackParamList, T>;

export function MissionOfferScreen({ navigation, route }: Props<'MissionOffer'>) {
  const [booking, setBooking] = useState<Booking | null>(null); const [loading, setLoading] = useState(false);
  useEffect(() => { api.booking(route.params.bookingId).then(setBooking); }, []);
  async function accept() { try { setLoading(true); await api.updateStatus(route.params.bookingId, 'DRIVER_EN_ROUTE'); navigation.replace('DriverNavigation', { bookingId: route.params.bookingId }); } finally { setLoading(false); } }
  async function refuse() { await api.refuse(route.params.bookingId); navigation.replace('DriverHome'); }
  if (!booking) return <AppScreen><Text style={ui.muted}>Chargement de la mission…</Text></AppScreen>;
  return <AppScreen><Header title="Nouvelle mission" subtitle="Répondez rapidement" onBack={() => navigation.goBack()} /><View style={styles.bell}><Ionicons name="notifications" size={44} color={colors.bg} /></View><Card style={{ borderColor: colors.yellow }}><View style={styles.between}><Pill label="NOUVELLE DEMANDE" tone="yellow" /><Money cents={booking.estimatedPriceCents} size={22} /></View><Text style={styles.title}>{issueLabel(booking.issueType)}</Text><Info icon="location" text={booking.pickupAddress} /><Info icon="navigate" text={`${booking.distanceKm.toFixed(1)} km de transport`} /><Info icon="person" text={booking.client?.firstName ?? 'Client'} /><Info icon="bicycle" text={booking.vehicle ? `${booking.vehicle.brand} ${booking.vehicle.model}` : 'Moto'} /></Card><PrimaryButton title="Accepter la mission" tone="green" onPress={accept} loading={loading} /><PrimaryButton title="Refuser" tone="red" onPress={refuse} /></AppScreen>;
}

export function DriverNavigationScreen({ navigation, route }: Props<'DriverNavigation'>) {
  const { token } = useAuth(); const [booking, setBooking] = useState<Booking | null>(null);
  useDriverLocation(route.params.bookingId, token);
  useEffect(() => { api.booking(route.params.bookingId).then(setBooking); }, []);
  if (!booking) return <AppScreen><Text style={ui.muted}>Préparation de l’itinéraire…</Text></AppScreen>;
  const mission = booking;
  async function openNavigation(preferWaze: boolean) { const lat = mission.pickupLatitude; const lng = mission.pickupLongitude; const waze = `waze://?ll=${lat},${lng}&navigate=yes`; const apple = `http://maps.apple.com/?daddr=${lat},${lng}&dirflg=d`; const google = `https://www.google.com/maps/dir/?api=1&destination=${lat},${lng}&travelmode=driving`; if (preferWaze && await Linking.canOpenURL(waze)) return Linking.openURL(waze); return Linking.openURL(Platform.OS === 'ios' ? apple : google); }
  return <AppScreen><Header title="Vers le client" subtitle={booking.reference} onBack={() => navigation.navigate('DriverHome')} /><View style={styles.map}><MapView style={StyleSheet.absoluteFill} initialRegion={{ latitude: booking.pickupLatitude, longitude: booking.pickupLongitude, latitudeDelta: .08, longitudeDelta: .08 }}><Marker coordinate={{ latitude: booking.pickupLatitude, longitude: booking.pickupLongitude }} title="Client" /></MapView></View><Card><Info icon="location" text={booking.pickupAddress} /><Info icon="person" text={booking.client?.firstName ?? 'Client'} /></Card><PrimaryButton title="Démarrer avec Waze" icon="navigate" onPress={() => openNavigation(true)} /><SecondaryButton title={Platform.OS === 'ios' ? 'Ouvrir dans Plans' : 'Ouvrir dans Google Maps'} icon="map" onPress={() => openNavigation(false)} /><SecondaryButton title="Message au client" icon="chatbubble" onPress={() => navigation.navigate('Chat', { bookingId: booking.id })} /><PrimaryButton title="Je suis arrivé" tone="green" onPress={async () => { await api.updateStatus(booking.id, 'DRIVER_ARRIVED'); navigation.replace('DriverArrival', { bookingId: booking.id }); }} /></AppScreen>;
}

export function DriverArrivalScreen({ navigation, route }: Props<'DriverArrival'>) {
  return <AppScreen scroll={false} style={{ justifyContent: 'space-between' }}><Header title="Arrivée sur place" subtitle="Confirmez la prise en charge" onBack={() => navigation.goBack()} /><View style={styles.center}><View style={styles.pin}><Ionicons name="location" size={55} color={colors.yellow} /></View><Text style={styles.title}>Vous êtes arrivé sur place</Text><Text style={styles.centerText}>Prévenez le client dans la messagerie si vous ne le trouvez pas.</Text></View><View style={{ gap: 10 }}><SecondaryButton title="Contacter dans l’application" icon="chatbubble" onPress={() => navigation.navigate('Chat', { bookingId: route.params.bookingId })} /><PrimaryButton title="Confirmer l’arrivée" onPress={() => navigation.navigate('PickupPhotos', { bookingId: route.params.bookingId })} /></View></AppScreen>;
}

export function PickupPhotosScreen({ navigation, route }: Props<'PickupPhotos'>) {
  const [photos, setPhotos] = useState<string[]>([]); const [loading, setLoading] = useState(false);
  async function pick() { const result = await ImagePicker.launchCameraAsync({ quality: .75 }); if (!result.canceled) setPhotos((old) => [...old, result.assets[0]!.uri]); }
  async function next() { try { setLoading(true); for (const uri of photos) await api.uploadPhoto(route.params.bookingId, 'PICKUP', uri); await api.updateStatus(route.params.bookingId, 'PICKED_UP'); navigation.replace('Transport', { bookingId: route.params.bookingId }); } finally { setLoading(false); } }
  return <AppScreen><Header title="Prise en charge" subtitle="Photos facultatives" onBack={() => navigation.goBack()} /><Text style={ui.muted}>Photographiez la moto si vous souhaitez documenter son état avant chargement. Cette étape peut être ignorée.</Text><View style={styles.photos}>{photos.map((uri) => <Image key={uri} source={{ uri }} style={styles.photo} />)}<Pressable onPress={pick} style={styles.photoAdd}><Ionicons name="camera" size={31} color={colors.yellow} /><Text style={styles.yellow}>Prendre une photo</Text></Pressable></View><PrimaryButton title={photos.length ? 'Valider et charger la moto' : 'Continuer sans photo'} onPress={next} loading={loading} /></AppScreen>;
}

export function TransportScreen({ navigation, route }: Props<'Transport'>) {
  const { token } = useAuth(); const [booking, setBooking] = useState<Booking | null>(null); const [started, setStarted] = useState(false); useDriverLocation(route.params.bookingId, token);
  useEffect(() => { api.booking(route.params.bookingId).then((b) => { setBooking(b); setStarted(b.status === 'IN_TRANSIT'); }); }, []);
  if (!booking) return <AppScreen><Text style={ui.muted}>Chargement…</Text></AppScreen>;
  const mission = booking;
  async function openDestination() { const lat = mission.destinationLatitude; const lng = mission.destinationLongitude; const waze = `waze://?ll=${lat},${lng}&navigate=yes`; if (await Linking.canOpenURL(waze)) return Linking.openURL(waze); return Linking.openURL(Platform.OS === 'ios' ? `http://maps.apple.com/?daddr=${lat},${lng}&dirflg=d` : `https://www.google.com/maps/dir/?api=1&destination=${lat},${lng}`); }
  async function start() { await api.updateStatus(mission.id, 'IN_TRANSIT'); setStarted(true); await openDestination(); }
  return <AppScreen><Header title="Chargement & transport" subtitle={booking.reference} onBack={() => navigation.navigate('DriverHome')} /><View style={styles.transportHero}><Ionicons name="car-sport" size={72} color={colors.yellow} /><Pill label={started ? 'TRANSPORT EN COURS' : 'MOTO CHARGÉE'} tone={started ? 'green' : 'yellow'} /></View><Card><Step done text="Dépanneur sur place" /><Step done text="Moto chargée" /><Step done={started} text="Transport vers la destination" /><Step text="Livraison au client / garage" /></Card><Card><Text style={ui.label}>DESTINATION</Text><Text style={ui.optionTitle}>{booking.destinationAddress}</Text></Card>{started ? <PrimaryButton title="Arrivé à destination" tone="green" onPress={() => navigation.navigate('Delivery', { bookingId: booking.id })} /> : <PrimaryButton title="Démarrer le transport" icon="navigate" onPress={start} />}<SecondaryButton title="Signaler un problème" danger icon="warning" onPress={() => Alert.alert('Incident signalé', 'Le support a été averti. Vous pouvez ajouter un message à la mission.')} /></AppScreen>;
}

export function DeliveryScreen({ navigation, route }: Props<'Delivery'>) {
  const [photos, setPhotos] = useState<string[]>([]); const [loading, setLoading] = useState(false); const [booking, setBooking] = useState<Booking | null>(null); const [cashReceived, setCashReceived] = useState(false);
  useEffect(() => { api.booking(route.params.bookingId).then(setBooking); }, []);
  async function pick() { const result = await ImagePicker.launchCameraAsync({ quality: .75 }); if (!result.canceled) setPhotos((old) => [...old, result.assets[0]!.uri]); }
  async function finish() { try { setLoading(true); await api.updateStatus(route.params.bookingId, 'DELIVERED'); for (const uri of photos) await api.uploadPhoto(route.params.bookingId, 'DELIVERY', uri); await api.updateStatus(route.params.bookingId, 'COMPLETED', { cashReceived: booking?.paymentMethod === 'CASH' ? cashReceived : undefined }); navigation.replace('MissionSummary', { bookingId: route.params.bookingId }); } catch (e) { Alert.alert('Mission non terminée', e instanceof Error ? e.message : 'Réessayez.'); } finally { setLoading(false); } }
  return <AppScreen><Header title="Livraison" subtitle="Dernière étape" onBack={() => navigation.goBack()} /><View style={styles.success}><Ionicons name="checkmark-circle" size={88} color={colors.green} /><Text style={styles.title}>Moto livrée</Text><Text style={styles.centerText}>Confirmez que la moto est arrivée à la destination prévue.</Text></View>{booking?.paymentMethod === 'CASH' ? <ToggleRow title="Paiement en espèces reçu" subtitle={`${((booking.finalPriceCents ?? booking.estimatedPriceCents) / 100).toFixed(2)} € remis par le client`} value={cashReceived} onValueChange={setCashReceived} /> : <Card><Info icon="card" text="Paiement par carte préautorisé" /></Card>}<SectionTitle>Photos finales facultatives</SectionTitle><View style={styles.photos}>{photos.map((uri) => <Image key={uri} source={{ uri }} style={styles.photo} />)}<Pressable onPress={pick} style={styles.photoAdd}><Ionicons name="camera" size={28} color={colors.yellow} /><Text style={styles.yellow}>Ajouter</Text></Pressable></View><PrimaryButton title="Terminer la mission" tone="green" onPress={finish} loading={loading} disabled={booking?.paymentMethod === 'CASH' && !cashReceived} /></AppScreen>;
}

export function MissionSummaryScreen({ navigation, route }: Props<'MissionSummary'>) {
  const [booking, setBooking] = useState<Booking | null>(null); useEffect(() => { api.booking(route.params.bookingId).then(setBooking); }, []);
  return <AppScreen><View style={styles.success}><Ionicons name="checkmark-circle" size={88} color={colors.green} /><Text style={styles.title}>Mission terminée</Text><Text style={styles.centerText}>Le client a été informé et le paiement a été déclenché.</Text></View>{booking ? <Card><View style={styles.between}><Text style={ui.muted}>Mission</Text><Text style={ui.optionTitle}>{booking.reference}</Text></View><View style={styles.between}><Text style={ui.muted}>Montant</Text><Money cents={booking.finalPriceCents ?? booking.estimatedPriceCents} size={23} /></View><Info icon="receipt" text="Compte rendu et facture enregistrés" /><Info icon="images" text={`${booking.photos?.length ?? 0} photo(s) jointe(s)`} /></Card> : null}<PrimaryButton title="Retour aux missions" onPress={() => navigation.replace('DriverHome')} /></AppScreen>;
}

function useDriverLocation(bookingId: string, token: string | null) { const socket = useRef<Socket | null>(null); useEffect(() => { let subscription: Location.LocationSubscription | undefined; (async () => { const permission = await Location.requestForegroundPermissionsAsync(); if (permission.status !== 'granted') return; socket.current = io(API_URL, { auth: { token } }); socket.current.emit('booking:join', bookingId); subscription = await Location.watchPositionAsync({ accuracy: Location.Accuracy.High, distanceInterval: 15, timeInterval: 5000 }, (location) => socket.current?.emit('location:update', { bookingId, latitude: location.coords.latitude, longitude: location.coords.longitude, heading: location.coords.heading })); })(); return () => { subscription?.remove(); socket.current?.disconnect(); }; }, [bookingId, token]); }
function Info({ icon, text }: { icon: keyof typeof Ionicons.glyphMap; text: string }) { return <View style={styles.info}><Ionicons name={icon} size={20} color={colors.yellow} /><Text style={styles.infoText}>{text}</Text></View>; }
function Step({ text, done }: { text: string; done?: boolean }) { return <View style={styles.info}><Ionicons name={done ? 'checkmark-circle' : 'ellipse-outline'} size={21} color={done ? colors.green : colors.muted} /><Text style={[styles.infoText, !done && { color: colors.muted }]}>{text}</Text></View>; }

const styles = StyleSheet.create({ bell: { width: 88, height: 88, borderRadius: 44, backgroundColor: colors.yellow, alignItems: 'center', justifyContent: 'center', alignSelf: 'center' }, between: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', gap: 10 }, title: { color: colors.text, fontSize: 24, fontWeight: '900', textAlign: 'center' }, info: { flexDirection: 'row', alignItems: 'center', gap: 10, minHeight: 31 }, infoText: { color: colors.text, flex: 1, fontWeight: '600' }, map: { height: 280, borderRadius: 18, overflow: 'hidden', borderWidth: 1, borderColor: colors.border }, center: { flex: 1, alignItems: 'center', justifyContent: 'center', gap: 14 }, pin: { width: 120, height: 120, borderRadius: 60, backgroundColor: colors.surface, alignItems: 'center', justifyContent: 'center' }, centerText: { color: colors.muted, textAlign: 'center', lineHeight: 21 }, photos: { flexDirection: 'row', flexWrap: 'wrap', gap: 10 }, photo: { width: 95, height: 95, borderRadius: 12 }, photoAdd: { width: 120, height: 95, borderRadius: 12, borderWidth: 1, borderColor: colors.yellow, borderStyle: 'dashed', alignItems: 'center', justifyContent: 'center', gap: 5 }, yellow: { color: colors.yellow, fontWeight: '700', fontSize: 12 }, transportHero: { alignItems: 'center', padding: 24, gap: 15 }, success: { alignItems: 'center', gap: 12, marginVertical: 20 } });
